### ISSUE TITLE
Question about profile cards

### ISSUE THREAD

**Issue by paralin** [paralin/Dota2#11]
~

**Comment by chancegraff** [comment]
Are CMsgDOTAMatch, CMsgDOTAProfileResponse, and CMsgDOTAProfileCard apart of this?

I noticed that a lot of the data in these is usually empty, even if I've got the requested Steam user added as a friend on the bot's account. Not sure if this is related or not; I figured maybe the data is in there but isn't being mapped on the back end?

**Comment by paralin** [comment]
The calls are in the library. The data returned is pretty much whatever the GC returns. There's very little manipulation there. 

The bot does not need to be friends with the target profile to see profile cards. Check that the target profile actually has profile cards set at the top right of their profile - other than that I'm not sure. I can look into it some more if you continue having problems.

**Comment by sbx320** [comment]
There are a few quirks with profile responses and profile cards:
- Profile Responses can be limited due to the pre-reborn "hide dota & steam profile" option. The message itself doesn't seem to be actively used by the Reborn client anymore and is more of a legacy component now.
- Profile Cards are rather slow to propagate between Valve server. So if you recently changed them on your profile it can take a while before showing up for your bot. I've had some instances where updating profile cards from US to EU took about a day, while others (most likely on the same Server instance) updated almost instantly.

However both of these messages should be working fine, so I'm not sure what would cause troubles for you.

**Comment by chancegraff** [comment]
The Profile Cards do seemingly include more data than the Profile and Match responses, but the latter two have mostly 0's and empty collections. They do include the data that's normally available through DOTA's API but it'd be cool to have access to the more in-depth data. I was unsure if it was because Source2 is still relatively new so this data is in there as a placeholder until they start filling it in with actual data in the future.

@sbx320 So, if I understand correctly, players who used Source and enabled the "hide" option will have the configuration carried over to Source 2 and in turn affect the data that's returned by the GC for these requests? I know there's a setting in the newer client that allows the player to "hide match data" from public requests, but I don't know if this is the same setting as it was in the original Source client.

Ultimately, I only need the cluster and salt data so I can download replays, but I was hoping I could easily access player MMR data through this. If not I'll just have to glean it from replay data, although I'm not sure if it's in there.

Here's what I'm seeing as a response for each (translated into JSON). I believe I remembered seeing some MMR definitions in the Protobuf for the Profile response that aren't showing up in the responses, but I'm not sure if I'm remembering correctly.

**Profile Response**

```
{  
   result:80,
   game_account_client:null,
   latest_matches:[  

   ],
   heroes:[  

   ],
   player_name:"",
   team_name:"",
   team_tag:"",
   team_logo:0,
   showcase_hero:null,
   league_passes:[  

   ],
   event_tickets:[  

   ],
   team_id:0,
   has_passport:false,
   featured_items:[  

   ],
   abandon_percent:0
}
```

**Match response**

```
   {  
      good_guys_win:false,
      duration:1718,
      startTime:1449023035,
      players:[  
         {  
            account_id:13484591,
            player_slot:0,
            hero_id:32,
            item_0:11,
            item_1:174,
            item_2:63,
            item_3:46,
            item_4:71,
            item_5:0,
            expected_team_contribution:0,
            scaled_metric:0,
            previous_rank:0,
            rank_change:0,
            solo_rank:false,
            kills:0,
            deaths:3,
            assists:2,
            leaver_status:0,
            gold:583,
            last_hits:66,
            denies:2,
            gold_per_min:226,
            XP_per_min:288,
            gold_spent:5805,
            hero_damage:1439,
            tower_damage:0,
            hero_healing:0,
            level:12,
            time_last_seen:0,
            player_name:"Spicy McHaggis",
            support_ability_value:0,
            feeding_detected:false,
            search_rank:0,
            search_rank_uncertainty:0,
            rank_uncertainty_change:0,
            hero_play_count:0,
            party_id:0,
            scaled_kills:0,
            scaled_deaths:0,
            scaled_assists:0,
            claimed_farm_gold:0,
            support_gold:0,
            claimed_denies:0,
            claimed_misses:0,
            misses:0,
            ability_upgrades:[  

            ],
            additional_units_inventory:[  

            ],
            custom_game_data:null
         },
         ...
      ],
      match_id:1973596542,
      tower_status:[  
         384,
         1983
      ],
      barracks_status:[  
         48,
         48
      ],
      cluster:112,
      first_blood_time:169,
      replay_salt:1937974775,
      server_ip:0,
      server_port:0,
      lobby_type:7,
      human_players:10,
      average_skill:0,
      game_balance:0,
      radiant_team_id:0,
      dire_team_id:0,
      leagueid:0,
      radiant_team_name:"",
      dire_team_name:"",
      radiant_team_logo:0,
      dire_team_logo:0,
      radiant_team_complete:0,
      dire_team_complete:0,
      positive_votes:0,
      negative_votes:0,
      game_mode:22,
      picks_bans:[  

      ],
      match_seq_num:0,
      replay_state:2,
      radiant_guild_id:0,
      dire_guild_id:0,
      radiant_team_tag:"",
      dire_team_tag:"",
      series_id:0,
      series_type:0,
      broadcaster_channels:[  

      ],
      engine:1,
      custom_game_data:null
   }
```

**Comment by paralin** [comment]
The original profile request call has been disabled completely on valves end and should not be used. Profile cards and other source 2 calls are the only thing that work now. Try nethooking the client to see the sequence when you view someone's profile.

**Comment by chancegraff** [comment]
@paralin Alright, I gotcha. I didn't realize those were old calls. I'll give that a shot and see what comes through. Thanks for the help.

**Comment by paralin** [comment]
Profile cards should work fine.
