### ISSUE TITLE
'Property' is ambiguous because multiple kinds of members with this name exist in class 'CMsgDOTAProfileCard.Slot'.

### ISSUE THREAD

**Issue by daggemarren** [paralin/Dota2#16]
Hi, i have a problem.

```
Dim msg = New ClientGCMsgProtobuf(Of CMsgDOTAProfileCard)(packetMsg)
Dim Slots = msg.Body.slots(0)
```

now my variable Slots contains ambiguous names like "(property) stat" and "(Class) Stat".
So anything under the property Slots can't be assigned to a new variable because it will return 

> 'stat' is ambiguous because multiple kinds of members with this name exist in class 'CMsgDOTAProfileCard.Slot'.

**Comment by paralin** [comment]
I don't understand your problem, really.

C# is the only supported language but it should work in any .net language, so VB is OK.

Here's the C# code for what you're talking about:

```
    private CMsgDOTAProfileCard.Slot.Stat _stat = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CMsgDOTAProfileCard.Slot.Stat stat
    {
      get { return _stat; }
      set { _stat = value; }
    }
```

There is only one property in the class called "stat" so I don't know what's going on here.

**Comment by daggemarren** [comment]
I run VS2015 and this is what i get.
[http://imgur.com/2ZEycq0](http://imgur.com/2ZEycq0)

**Comment by sbx320** [comment]
This issue is likely caused by VB being case insensitive unlike C#. For VB the class Stat is the same as the property stat. 

So for example the following is disallowed in VB:

``` VB
Public Class Slot 
    Public Class Stat
    End Class

    Public ReadOnly Property stat As Stat
        Get
            Return New Stat()
        End Get
    End Property
End Class
```

error BC30260: 'stat' is already declared as 'Class Stat' in this class in line 5.

You're also unable to use the class/property when created in a .NET language where the equivalent of the above is legal (C#), since VB does not differenciate between class and property. This makes it impossible to use the stats part of the profile cards in VB.  It might be possible to access the fields using Reflection, but my knowledge of VB is far too limited to assist with that.

I'm not sure if this is fixable, especially given the files are autogenerated.

**Comment by paralin** [comment]
@sbx320 Thanks for the clarification.

As I see VB as being the worst language on earth I'm not going to pursue trying to address this. Use a decent language like C#! :)

**Comment by daggemarren** [comment]
Thanks for the answers guys. im going to convert my code then.

**Comment by arslanmkhan** [comment]
I am receiving the exact same error and i am using csharp. Infact i am just building dota2 library without any modification in source. Somehow dota2 is referencing itself
i think this project have some compatibility issues with vs2015 and .net framework 4.6,

**Comment by paralin** [comment]
Are you using Dota2.sln or Dota2.dnx.sln

**Comment by paralin** [comment]
As of the latest update I can confirm this works with .net 4.6 and vs2015.

**Comment by arslanmkhan** [comment]
I investigated it further and was able to resolve this. I haven't found a concrete reason for this though. My guess is this issue is occurring because nuget packages were not restored automatically and i tried restoring them manually somehow i have dota2 in .nugget folder which was referenced by dota2 project although this reference wasn't available under the references section of project. When i deleted dota2 from ,nugget folder everything started working properly
