### ISSUE TITLE
Unable to access some Dota enums

### ISSUE THREAD

**Issue by uside** [paralin/Dota2#20]
Trying to use following in my code:
`Dota2.GC.Dota.Internal.DOTA_GameMode.DOTA_GAMEMODE_CM`
Visual Studio says:
`The type name 'DOTA_GAMEMODE_CM' does not exist in the type 'DOTA_GameMode'`

This is not critical, but not obvious behavior, I think

**Comment by paralin** [comment]
That's strange... 

The generated code uses this in this way: https://github.com/paralin/Dota2/blob/master/src/Dota2/Base/Generated/GC/Dota/MsgGCCommon.cs#L5325

It's defined as a pretty standard enum here: https://github.com/paralin/Dota2/blob/master/src/Dota2/Base/Generated/GC/Dota/MsgSharedEnums.cs#L248

You should get auto-completion just fine.

I'm going to close this since I think it's an Intellisense bug or something else, and there's nothing I can really do to fix this. Let me know if you need more help, though.
